name: Build TASauria

on:
  push:
  pull_request:
    types: [ opened, edited ]
  workflow_dispatch:

jobs:
  build-plugin:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        bizhawk:
          - { HEAD: "master", INCLUDE_COMMIT: true }
          - { HEAD: "2.10", INCLUDE_COMMIT: false }
          - { HEAD: "2.9.1", INCLUDE_COMMIT: false }
          - { HEAD: "2.9", INCLUDE_COMMIT: false }
          - { HEAD: "2.8", INCLUDE_COMMIT: false }
          - { HEAD: "2.7", INCLUDE_COMMIT: false }
          - { HEAD: "2.6.3", INCLUDE_COMMIT: false }
          - { HEAD: "2.6.2", INCLUDE_COMMIT: false }
          - { HEAD: "2.6.1", INCLUDE_COMMIT: false }
          - { HEAD: "2.6", INCLUDE_COMMIT: false }
        target:
          - { BIZHAWK_TARGET: "Release", TASAURIA_TARGET: "Release" }
    name: "Build TASauria plugin for BizHawk ${{ matrix.bizhawk.HEAD }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - id: tasauria-checkout
        name: Unshallow repository and get version
        shell: bash
        run: |
          git fetch --prune --unshallow origin
          export TASAURIA_REV="$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          echo "TASAURIA_REV=${TASAURIA_REV}" >> $GITHUB_OUTPUT

      - id: bizhawk-checkout
        name: Checkout the appropriate BizHawk version
        shell: bash
        env:
          BIZHAWK_HEAD: ${{ matrix.bizhawk.HEAD }}
          INCLUDE_COMMIT: ${{ matrix.bizhawk.INCLUDE_COMMIT && '1' || '' }}
        run: |
          cd BizHawk
          git fetch --prune --unshallow origin
          git checkout "origin/${BIZHAWK_HEAD}"
          export BIZHAWK_REV="$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          if [ -z "${INCLUDE_COMMIT}" ]; then
            export BIZHAWK_VERSION="${BIZHAWK_HEAD}";
          else
            export BIZHAWK_VERSION="${BIZHAWK_HEAD}.rev${BIZHAWK_REV}";
          fi
          echo "BIZHAWK_REV=${BIZHAWK_REV}" >> $GITHUB_OUTPUT
          echo "BIZHAWK_VERSION=${BIZHAWK_VERSION}" >> $GITHUB_OUTPUT
          cd ..

      - name: Build BizHawk
        shell: pwsh
        env:
          BIZHAWK_TARGET: ${{ matrix.target.BIZHAWK_TARGET }}
        run: |
          cd BizHawk
          dotnet build BizHawk.sln -c "${env:BIZHAWK_TARGET}"
          cd ..

      - name: Build TASauria
        shell: pwsh
        env:
          TASAURIA_TARGET: ${{ matrix.target.TASAURIA_TARGET }}
        run: |
          cd TASauriaPlugin
          dotnet build TASauriaPlugin.sln -c "${env:TASAURIA_TARGET}"
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TASauriaPlugin.rev${{ steps.tasauria-checkout.outputs.TASAURIA_REV }}_BizHawk.${{ steps.bizhawk-checkout.outputs.BIZHAWK_VERSION }}
          path: BizHawk/output/ExternalTools/*
